Repository Rutuj-Runwal/RR-Adblocker, pull requests merged in 2022-10, with the labels that each got.

#4 Added Version Log
  ChangeLog.md
Labels: hacktoberfest

#5 Removed typo
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#9 Updated Errors and Malware Protection
  background.js
  block_2.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#11 Safari compatibility
  makefile
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#28 created contributors page and options buttons
  contributors.html
  contributors.js
  options.html
Labels: enhancement, hacktoberfest-accepted

#52 added indonesiantranslate
  _locales/id/messages.json
Labels: documentation, hacktoberfest-accepted

#66 Fixed responsivity issue on mobile browser
  Popup.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#62 Added Gujarati language translation regarding issue #44
  _locales/gu/messages.json
Labels: hacktoberfest-accepted

#68 Added Malayalam language regarding issue #44
  _locales/ml/message.json
Labels: good first issue, hacktoberfest-accepted

#69 Translated in Bengali.
  _locales/be/messages.json
Labels: good first issue, hacktoberfest-accepted

#63 Add Romanian localization
  _locales/ro/messages.json
Labels: documentation, good first issue, hacktoberfest-accepted
